# Generated by Django 3.0.5 on 2020-04-02 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ideia',
            fields=[
                ('id_ideia', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=20)),
                ('descricao', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('AN', 'Analise'), ('AP', 'Aprovado'), ('EX', 'Excluido')], max_length=2)),
                ('dt_exclusao', models.DateTimeField(blank=True, null=True)),
                ('dt_criacao', models.DateTimeField()),
                ('link_youtube', models.CharField(max_length=200)),
                ('material_complementar', models.CharField(blank=True, max_length=200, null=True)),
                ('imagem', models.CharField(max_length=200)),
                ('compartilhamentos', models.IntegerField(default=0)),
            ],
        ),
    ]
