# Generated by Django 3.0.5 on 2020-04-07 11:12

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Realizador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=20)),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('excluido_em', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=15)),
                ('descricao', models.CharField(max_length=200)),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('excluido_em', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ideia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=20)),
                ('descricao', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('AN', 'Analise'), ('AP', 'Aprovado'), ('EX', 'Excluido')], max_length=2)),
                ('link_youtube', models.CharField(max_length=200)),
                ('material_complementar', models.CharField(blank=True, max_length=200, null=True)),
                ('caminho_imagem', models.CharField(max_length=200)),
                ('impacto', models.IntegerField(default=0)),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('excluido_em', models.DateTimeField(blank=True, null=True)),
                ('realizador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ideias.Realizador')),
                ('tema', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ideias.Tema')),
            ],
        ),
    ]
