# Generated by Django 3.0.5 on 2020-04-08 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideias', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realizador',
            name='email',
            field=models.CharField(max_length=50),
        ),
    ]
